version: '3.4'

services:
  omniepdv.api:
    image: ${DOCKER_REGISTRY-}omniepdvapi
    build:
      context: .
      dockerfile: OmniePDV.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"